name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.save-artifact.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: |
          cd demo
          mvn clean install -DskipTests

      - name: Save JAR as artifact
        id: save-artifact
        uses: actions/upload-artifact@v3
        with:
          name: demo-jar
          path: demo/target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: |
          cd demo
          mvn test

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: demo-jar
          path: demo/target/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: demo
          file: demo/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/resourceflow-ai:latest
            ghcr.io/${{ github.repository }}/resourceflow-ai:${{ github.sha }}
